version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: always
    
    # Port configuration
    ports:
      - "127.0.0.1:5678:5678"  # Exposes n8n's UI & API (bound to localhost only)
    
    # Environment variables
    environment:
      # Basic Authentication
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      
      # Server configuration
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_TUNNEL_URL=http://localhost:5678/
    
    # Volumes for persistent data and file storage
    volumes:
      - n8n_data:/home/node/.n8n  # Persists workflows, credentials, and settings
      - ./local-files:/files       # Local directory for file operations

# Named volume for persistent data storage
volumes:
  n8n_data:

# External network for connecting to other services
networks:
  web:
    external: true
